export type PackageCategory = "clasicos" | "huntrix" | "sensorial";

export interface PartyPackage {
  id: string;
  category: PackageCategory;
  name: string;
  price: number;
  priceLabel: string; // "S/ 699"
  duration: string;
  includes: string[];
  gifts: string[];
  courtesy?: string[];
  featured?: boolean;
}

export const CATEGORY_LABELS: Record<PackageCategory, string> = {
  clasicos: "Shows Clásicos y Temáticos",
  huntrix: "Especial Huntrix (Temático)",
  sensorial: "Sensorial & Estimulación",
};

export const PACKAGES: PartyPackage[] = [
  // ---------- CLÁSICOS Y TEMÁTICOS ----------
  {
    id: "paquete-basico",
    category: "clasicos",
    name: "Paquete Básico",
    price: 250,
    priceLabel: "S/ 250",
    duration: "1h 30 min",
    includes: [
      "Animadora vestida de acorde a los colores de la temática",
      "Asistente de sonido",
      "Equipo de sonido 8' + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: ["Globos pencil", "Bola de luz rítmica", "Bazooka de burbujas", "Bombarda"],
  },
  {
    id: "mi-fiesta",
    category: "clasicos",
    name: "Mi Fiesta",
    price: 399,
    priceLabel: "S/ 399",
    duration: "1h 30 min",
    includes: [
      "Animadora vestida de acorde a la temática",
      "Muñeco temático o bailarín(a)",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido 8' + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: ["Globos pencil", "Bola de luz rítmica", "Bazooka de burbujas", "Bombarda", "AnggelyStickers para nombres"],
    courtesy: ["Túnel Mágico"],
  },
  {
    id: "super-fiesta",
    category: "clasicos",
    name: "Super Fiesta",
    price: 559,
    priceLabel: "S/ 559",
    duration: "2h",
    includes: [
      "Animadora vestida de acorde a la temática",
      "Bailarín(a) temático",
      "Muñeco o personaje temático",
      "Sonidista bailarín(a)",
      "Equipo de sonido + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: ["Globos pencil", "Bola de luz rítmica", "Bazooka de burbujas", "Pulseras LED", "AnggelyStickers para nombre"],
    courtesy: ["Encapsulador de burbujas", "Túnel Mágico"],
  },
  {
    id: "mega-fiesta",
    category: "clasicos",
    name: "Mega Fiesta",
    price: 699,
    priceLabel: "S/ 699",
    duration: "2h",
    includes: [
      "Animadora vestida de acorde a la temática",
      "4 Bailarines o 2 muñecos temáticos",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: [
      "Globos pencil",
      "Bola de luz rítmica",
      "Bazooka de burbujas",
      "AnggelyStickers para nombre",
      "Pulseras LED",
      "Cuenta cuentos con títeres",
    ],
    courtesy: ["Túnel Mágico", "2 Bombardas", "Pitos y matracas"],
  },
  {
    id: "fiesta-premium",
    category: "clasicos",
    name: "Fiesta Premium",
    price: 899,
    priceLabel: "S/ 899",
    duration: "2h 30 min",
    includes: [
      "Animadora vestida de acorde a la temática",
      "2 Bailarin(e)s",
      "4 Muñecos o personajes temáticos",
      "Encapsulador de burbujas con pomperos",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: [
      "Accesorios para hora loca (globos pencil, 2 bombardas, 24 pitos y 24 matracas)",
      "Bola de luz rítmica",
      "Bazooka de burbujas",
      "AnggelyStickers para nombre",
      "1 Arlequín para Mini Hora Loca",
    ],
    courtesy: ["Túnel Mágico", "Cañón lanza confetti", "Cuenta cuentos con títeres"],
  },
  {
    id: "mega-fiesta-premium",
    category: "clasicos",
    name: "Mega Fiesta Premium",
    price: 1299,
    priceLabel: "S/ 1299",
    duration: "2h 30 min",
    includes: [
      "Animadora totalmente caracterizada con la temática",
      "6 Bailarines temáticos",
      "4 Muñecos temáticos (segundo tiempo)",
      "Bailes con coreografías",
      "Encapsulador de burbujas con pomperos",
      "Canta y gana con módulo",
      "Máquina de humo",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido 15' + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday con torta de burbujas",
    ],
    gifts: [
      "40 minutos de caritas pintadas o Glitter Bar con pedrería",
      "Accesorios para hora loca (globos pencil, 2 bombardas, 24 pitos y 24 matracas)",
      "2 Bolas de luz rítmica",
      "1 Luz láser",
      "Bazooka de burbujas",
      "AnggelyStickers para nombre",
      "1 Arlequín para Mini Hora Loca",
    ],
    courtesy: ["Túnel Mágico", "Cañón lanza confetti"],
    featured: true,
  },

  // ---------- ESPECIAL HUNTRIX ----------
  {
    id: "huntrix-basico",
    category: "huntrix",
    name: "Huntrix Básico",
    price: 319,
    priceLabel: "S/ 319",
    duration: "1h 30 min",
    includes: [
      "Animadora Rumi caracterizada",
      "Equipo de sonido 8' + Micrófono inalámbrico",
      "Asistente de sonido",
      "Juegos de competencia",
      "Canta juegos con accesorios",
      "Torta de burbujas",
      "Pistola de burbujas",
      "Hora loca",
      "Rompe la piñata",
      "Cantamos Happy Birthday",
    ],
    gifts: ["25 Globos pencil", "Bola de luz rítmica"],
  },
  {
    id: "huntrix-medio",
    category: "huntrix",
    name: "Huntrix Medio",
    price: 549,
    priceLabel: "S/ 549",
    duration: "1h 30 min",
    includes: [
      "Animadora Rumi caracterizada",
      "2 señoritas caracterizadas (Zoey y Mira)",
      "Equipo de sonido + Micrófono inalámbrico",
      "Asistente de sonido",
      "Juegos de competencia con implementos (circuito)",
      "Canta juegos con accesorios",
      "Torta de burbujas",
      "Bazooka de burbujas",
      "Hora loca",
      "Rompe la piñata",
      "Cantamos Happy Birthday",
    ],
    gifts: ["25 Globos pencil", "30 stickers para nombre", "Bola de luz rítmica"],
  },
  {
    id: "huntrix-deluxe",
    category: "huntrix",
    name: "Huntrix Deluxe",
    price: 699,
    priceLabel: "S/ 699",
    duration: "2h 30 min",
    includes: [
      "Animadora vestida a corde a los colores de la temática",
      "3 Personajes Huntrix: Rumi, Zoey y Mira",
      "Equipo de sonido + Micrófono inalámbrico",
      "Asistente de sonido",
      "Juegos de competencia con implementos (circuito)",
      "Bailes y coreografías",
      "Canta juegos con accesorios",
      "Torta de burbujas",
      "Cañón lanza confetti",
      "Máquina de humo para presentación y bailes",
      "Túnel Mágico",
      "Bazooka de burbujas",
      "Hora Loca",
      "Rompe la piñata",
      "Cantamos Happy Birthday",
    ],
    gifts: [
      "30 minutos de caritas pintadas",
      "30 Globos pencil",
      "24 pitos y 24 matracas",
      "30 stickers para nombre",
      "Bola de luz rítmica",
    ],
    featured: true,
  },

  // ---------- SENSORIAL & ESTIMULACIÓN ----------
  {
    id: "sensorial-basico",
    category: "sensorial",
    name: "Sensorial Básico",
    price: 359,
    priceLabel: "S/ 359",
    duration: "1h 30 min",
    includes: [
      "Dos señoritas encargadas",
      "Un equipo de sonido 8' con micrófono",
      "Canta juegos con accesorios (pañuelos de colores, maracas y panderetas, pompones)",
      "Manta con pelotas",
      "Medusas de mar",
      "Patos con aros",
      "Recoge pelotas",
      "Baile con burbujas",
      "Canción con títere de mano",
      "Romper la piñata",
      "Cantamos Cumpleaños Feliz",
    ],
    gifts: ["1 Bandeja de cortecía (Orbitz o arroz con accesorios)", "Bazooka de burbujas", "Piso para juegos"],
  },
  {
    id: "sensorial-burbujas-2",
    category: "sensorial",
    name: "Sensorial Burbujas · Paquete 2",
    price: 599,
    priceLabel: "S/ 599",
    duration: "1h 45 min",
    includes: [
      "Dos señoritas encargadas",
      "Sonidista coordinador",
      "Un equipo de sonido 8' con micrófono",
      "Canta juegos con accesorios (pañuelos, pompones, maracas y panderetas)",
      "Encapsulador de burbujas",
      "Piscina con pelotas",
      "Manta con pelotas",
      "Medusas de mar",
      "Recoge pelotas",
      "Baile con burbujas",
      "Dos bandejas sensoriales de 30 min (orbitz personalizado, arroz temático, pompones con accesorios)",
      "Romper la piñata",
      "Cantamos Cumpleaños Feliz",
    ],
    gifts: ["Bazooka de burbujas", "Piso para juegos", "Túnel Mágico"],
  },
  {
    id: "sensorial-burbujas-3",
    category: "sensorial",
    name: "Sensorial Burbujas · Paquete 3",
    price: 859,
    priceLabel: "S/ 859",
    duration: "2h 30 min",
    includes: [
      "Dos señoritas encargadas",
      "Sonidista / Coordinador",
      "Asistente para organizar juegos",
      "Canta juegos con accesorios",
      "Show de burbujas / Encapsulador y pomperos",
      "Piscina con pelotas",
      "Manta con pelotas",
      "Medusas de mar",
      "Canciones con títere de mano",
      "Cuatro bandejas sensoriales (arena mágica, botellas con arroz personalizado, pompones con carritos de excavación, masas moldeables)",
      "4 Atriles con temperas para pintar, incluye mandil",
      "Romper la piñata",
      "Cantamos Cumpleaños Feliz",
    ],
    gifts: ["30 minutos de caritas pintadas", "Bazooka de burbujas", "Piso para juegos", "Túnel Mágico"],
    featured: true,
  },
  {
    id: "burbupack-1",
    category: "sensorial",
    name: "BurbuPack 1",
    price: 359,
    priceLabel: "S/ 359",
    duration: "1h 45 min",
    includes: [
      "Animadora vestida de acorde a la temática",
      "Encapsulador de burbuja",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido 8' + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: ["Globos pencil", "Bola de luz rítmica", "Bazooka de burbujas", "Bombarda"],
  },
  {
    id: "burbupack-2",
    category: "sensorial",
    name: "BurbuPack 2",
    price: 499,
    priceLabel: "S/ 499",
    duration: "1h 45 min",
    includes: [
      "Animadora vestida de acorde a la temática",
      "2 Bailarines temáticos o 1 muñeco temático",
      "Encapsulador de burbuja",
      "Asistente de sonido / Coordinador",
      "Equipo de sonido 8' + Micrófono inalámbrico",
      "Juegos divertidos y recreativos (circuitos)",
      "Canta juegos con accesorios",
      "Mini hora loca",
      "Rompe la piñata",
      "Happy Birthday",
    ],
    gifts: ["Globos pencil", "Bola de luz rítmica", "Bazooka de burbujas", "Bombarda"],
  },
];

export function getPackagesByCategory(category: PackageCategory) {
  return PACKAGES.filter((p) => p.category === category);
}
